

// try catch statements are used for error handling

// try catch statements keeps running a program when it encounters an error

try{
    
    console.log(a+b)

}
 catch(err) {

   console.log(err);

   console.log("there was an error")

   console.log("error was catched in a err object")

}

console.log("this code does not stop working")





